name: dgraph
version: 0.0.1
author: Richard Lincoln <r.w.lincoln@gmail.com>
description: Visualisation and interaction with node-edge graphs
homepage: https://github.com/rwl/dgraph.dart
dependencies:
  image: any
  intl: any
dev_dependencies:
  browser: any
  unittest: any
