name: board
version: 0.0.1-alpha.1
author: Richard Lincoln <r.w.lincoln@gmail.com>
description: Interactive node-edge graph visualisation
homepage: https://github.com/rwl/board.dart
dependencies:
  color: any
  crypto: any
  dart_web_toolkit: any
  image: any
  intl: any
  unicode_helper: any
  xml: any
  xmlstream: any
dev_dependencies:
  browser: any
  unittest: any
