name: dgraph
version: 0.0.1
description: Visualisation and interaction with node-edge graphs
author: Richard Lincoln <r.w.lincoln@gmail.com>
homepage: https://github.com/rwl/dgraph.dart
dependencies:
  intl: any
dev_dependencies:
  browser: any
  unittest: any
